url: https://stpeterspeterborough.ca
#baseurl:
future: true
strict_front_matter: true
timezone: America/Toronto
exclude: [ "source", "util", "media", "temp" ]

styles_path:           /styles/
scripts_path:          /scripts/
forms_path:            /forms/
documents_path:        /documents/
images_path:           /images/
banner_images_path:    /images/banner/
slideshow_images_path: /images/slideshow/
giving_images_path:    /images/giving/
social_images_path:    /images/social/
schedule_images_path:  /images/schedule/
bulletin_images_path:  /images/bulletins/
clergy_images_path:    /images/clergy/
ministry_images_path:  /images/ministries/
sacrament_images_path: /images/sacraments/
history_images_path:   /images/history/
